export { AnimalAvatar } from './AnimalAvatar'
export { AnimalsToolbar } from './AnimalsToolbar'
export { AnimalsTable } from './AnimalsTable'
export { AnimalViewDialog } from './AnimalViewDialog'
export { AnimalsPage as Animals } from './pages/AnimalsPage'
